BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
SPLIT_KEYBOARD = yes
ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes

LTO_ENABLE = yes
VIA_ENABLE = yes
